branch-defaults:
  main:
    environment: Gotham
    group_suffix: null
  rsIntegration:
    environment: Gotham
environment-defaults:
  Gotham2:
    branch: null
    repository: null
global:
  application_name: Gotham
  branch: null
  default_ec2_keyname: null
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
