version: 2

jobs:
  build:
    docker: # Run the steps using Docker
      - image:  circleci/golang:1.15.2
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD

    steps:
      - checkout #checkout source code to local working directory

      - run: 
          name: Getting dependencies
          command: go get -v -t -d ./...
      
      - run:
          name: Run unit tests
          command: go test -v ./...

workflows:
  version: 2
  build-workflow:
    jobs:
      - build